# compose.yml (devcontainer)
services:
  devcontainer:
    build: .
    volumes:
      - ..:/workspace
      # - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shared-network # Use the shared network
    command: sleep infinity
    cap_add:
      - NET_ADMIN
      - NET_RAW
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  shared-network:
    name: shared-network # Fixed name that MCP services can reference
    driver: bridge
