services:
  app:
    build: .
    ports:
      - "{{ cookiecutter.app_port }}:{{ cookiecutter.app_port }}" # Exposed to host
    networks:
      - shared # Can communicate with devcontainer
      - app-network # Can communicate with its own postgres
    environment:
      - DATABASE_URL=postgresql://{{ cookiecutter.postgres_user }}:{{ cookiecutter.postgres_password }}@postgres:5432/{{ cookiecutter.postgres_db }}
    depends_on:
      - postgres

  postgres:
    image: postgres:{{ cookiecutter.postgres_version }}-alpine
    environment:
      POSTGRES_DB: {{ cookiecutter.postgres_db }}
      POSTGRES_USER: {{ cookiecutter.postgres_user }}
      POSTGRES_PASSWORD: {{ cookiecutter.postgres_password }}
    networks:
      - app-network # Isolated to app only
    # Note: No 'ports' - only accessible from app

networks:
  shared:
    external: true # References the shared network from devcontainer
    name: devcontainer_shared # Docker Compose prefixes with folder name
  app-network:
    internal: true # App's private network
